### ISSUE TITLE
Issue with pulling episode art

### ISSUE THREAD

**Issue by Sheepykin** [JordyAlkema/Youtube-DL-Agent.bundle#9]
So I ran into an issue where some of the art for many episodes was not working for some reason. I would refresh the metadata and plex would not pull in the .webp or .png image files made by Youtube-dl. 

In the coding at line 71 and I changed it from:
for extension in [".jpg", ".webp"]:

To:
for extension in ['jpg', 'jpeg', 'png', 'tiff', 'gif', 'jp2', 'webp']:

And suddenly all of my episode art was being pulled in. This line now matches line 82 in the ZeroQI agent. I am unsure if that fixed it or something else randomly let it work.

And example of this was the episodes from Markiplier's Outlast 2 playthrough.

**Comment by JordyAlkema** [comment]
Hi, I added the image extensions you mentioned, hopefully this fixes the issue. Feel free to reopen this issue if it doesn't
